const WRONG_DATA = 400;
const NOT_FOUND = 404;
const DEFAULT_ERROR = 500;
const SUCCESS = 200;
const AUTH_ERROR = 401;
const DB_ERROR = 409;
const FORBIDDEN = 403;
const CREATED = 201;
module.exports = {
  WRONG_DATA, NOT_FOUND, DEFAULT_ERROR, SUCCESS, AUTH_ERROR, DB_ERROR, FORBIDDEN, CREATED,
};
